### ISSUE TITLE
--unused seems to choke on async keyword

### ISSUE THREAD

**Issue by jrnail23** [davidmfoley/node-trucker#10]
When running `trucker --unused` I got a `SyntaxError: Unexpected token` corresponding to the `async` keyword in the following (partial) source code:

```js
export const fetchLookup = query =>
  async dispatch => {
    const fetchUsers = {
      type: DD_FETCH_USERS,
      queue: DD_FETCH_USERS,
      query
    }
...
```

We use Babel v6.9.0, including `babel-preset-stage-0`, `babel-plugin-transform-async-to-module-method`, and `babel-preset-es2015` (among other presets/plugins).

**Comment by davidmfoley** [comment]
Thanks for the report. How do you configure babel? Do you use a babelrc?

**Comment by jrnail23** [comment]
Hi @davidmfoley, sorry I didn't see your reply sooner -- you were quicker than I thought!

Here's our `.babelrc`:
```json
{
  "plugins": [
    [
      "transform-async-to-module-method",
      {
        "module": "bluebird",
        "method": "coroutine"
      }
    ],
    "transform-decorators-legacy",
    "add-module-exports"
  ],
  "presets": [
    "es2015-node5",
    "stage-0"
  ]
}
```

Just let me know if you need more info.  Thanks for looking into this!

**Comment by davidmfoley** [comment]
@jrnail23 I fixed this specific case by including a few more plugins when configuring babylon. It would be cool to handle this by reading any ```.babelrc``` that is found (or allowing one to specify a .babelrc) but that would be more work than I have time for today.

**Comment by jrnail23** [comment]
@davidmfoley, is there a workaround that you could recommend for now?

**Comment by davidmfoley** [comment]
If you grab 0.7.1 from npm, it should handle this case (ref: https://github.com/davidmfoley/node-trucker/blob/master/test/findRequires_spec.js#L35)

It's hard to say whether it will handle every case in your source code because trucker doesn't do any parsing or importing of custom babel plugins -- it just enables a bunch of the default babylon (babel frontend) plugins, kitchen-sink style.

Let me know if you have any problems and thanks again for the report.

**Comment by davidmfoley** [comment]
@jrnail23 Closing this; let me know if you have any other issues -- really appreciate the report.
